development:
  adapter: postgresql
  database: fire_coverage_development
  host: localhost
  encoding: utf8

test: &TEST
  adapter: postgresql
  database: fire_coverage_test
  host: localhost
  encoding: utf8
  min_messages: warning

cucumber:
  <<: *TEST

staging:
  adapter: postgresql
  database: fire_coverage_development

production:
  adapter: postgresql
  database: fire_coverage_development
